// Curated Font Awesome solid icon names for the skill editor picker.
// Any other free-solid icon name typed in still works.
export const ICONS = [
  'anchor', 'arrows-up-down-left-right', 'award', 'bag-shopping', 'bandage', 'building-columns', 'battery-full',
  'bell', 'binoculars', 'bolt', 'bomb', 'bone', 'book', 'book-skull', 'box', 'boxes-stacked', 'brain',
  'briefcase', 'briefcase-medical', 'building', 'bullhorn', 'bullseye', 'burger', 'bus', 'calculator',
  'camera', 'campground', 'candy-cane', 'capsules', 'car', 'car-battery', 'car-burst', 'car-side', 'carrot',
  'cart-shopping', 'cash-register', 'chart-line', 'check', 'chess-knight', 'circle-nodes', 'city',
  'clipboard-list', 'clock', 'cloud', 'code', 'coins', 'compass', 'compact-disc', 'cookie-bite', 'couch',
  'credit-card', 'crosshairs', 'crow', 'crown', 'cube', 'diamond', 'dice', 'dna', 'dollar-sign', 'door-open',
  'dove', 'dragon', 'droplet', 'drum', 'dumbbell', 'ear-listen', 'egg', 'envelope', 'eye', 'eye-slash',
  'feather', 'file-invoice-dollar', 'fingerprint', 'fire', 'fire-extinguisher', 'fish', 'fish-fins', 'flask',
  'flask-vial', 'gas-pump', 'gauge-high', 'gavel', 'gem', 'ghost', 'gift', 'glasses', 'gun', 'hammer', 'hand',
  'hand-fist', 'hand-holding-dollar', 'hand-holding-heart', 'hand-sparkles', 'handcuffs', 'handshake',
  'hard-drive', 'hat-cowboy', 'headphones', 'heart', 'heart-pulse', 'helicopter', 'helmet-safety', 'horse',
  'hourglass-half', 'house', 'id-card', 'industry', 'jet-fighter', 'key', 'keyboard', 'kit-medical',
  'kitchen-set', 'landmark', 'laptop-code', 'leaf', 'lightbulb', 'link', 'lock', 'lock-open', 'magnet',
  'magnifying-glass', 'map', 'map-location-dot', 'mask', 'masks-theater', 'medal', 'microchip', 'microphone',
  'money-bill', 'money-bill-trend-up', 'moon', 'motorcycle', 'mountain', 'mug-hot', 'network-wired',
  'oil-can', 'paintbrush', 'palette', 'paper-plane', 'parachute-box', 'paw', 'people-group', 'person-digging',
  'person-running', 'phone', 'pills', 'pizza-slice', 'plane', 'plug', 'prescription-bottle', 'puzzle-piece',
  'radiation', 'radio', 'recycle', 'ring', 'road', 'robot', 'rocket', 'route', 'ruler-combined', 'sack-dollar',
  'satellite-dish', 'scale-balanced', 'scissors', 'screwdriver-wrench', 'scroll', 'seedling', 'server',
  'shield', 'shield-halved', 'ship', 'shirt', 'shoe-prints', 'shop', 'shuffle', 'signal', 'sitemap', 'skull',
  'skull-crossbones', 'spa', 'spider', 'splotch', 'spray-can-sparkles', 'star', 'stethoscope', 'stopwatch',
  'suitcase', 'sun', 'syringe', 'tablet-screen-button', 'tag', 'taxi', 'tents', 'terminal', 'toolbox',
  'tooth', 'tornado', 'tractor', 'traffic-light', 'train', 'tree', 'trophy', 'truck', 'truck-monster',
  'umbrella', 'unlock', 'unlock-keyhole', 'user-ninja', 'user-secret', 'user-tie', 'utensils', 'van-shuttle',
  'vault', 'vial', 'video', 'volleyball', 'wallet', 'wand-magic-sparkles', 'warehouse', 'water', 'weight-hanging',
  'wheat-awn', 'wifi', 'wind', 'wine-bottle', 'wrench',
]
